version: '3.3'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --innodb_lock_wait_timeout=2
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: drprj001/rails:latest
    environment:
      - TZ=Asia/Tokyo
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_NAME=development
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  bundle:
  mysql-data:
